{
 "title": "Sentinel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sentinel_master_info{master_ip=\"192.168.100.114\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "sentinel_sentinels_current up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentinel_sentinels_current{state=\"up\", instance=\"192.168.100.115:9478\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sentinel_sentinels_current down",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentinel_sentinels_current{state=\"down\",instance=\"192.168.100.113:9478\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sentinel_master_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sentinel_master_info{master_name=\"mymaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"192.168.100.113:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_max_fds{instance=\"192.168.100.114:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_max_fds{instance=\"192.168.100.115:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"192.168.100.113:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"192.168.100.114:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"192.168.100.115:9478\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"192.168.100.113:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_open_fds{instance=\"192.168.100.114:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_open_fds{instance=\"192.168.100.115:9478\", job=\"sentinel_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"192.168.100.113:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_start_time_seconds{instance=\"192.168.100.114:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_start_time_seconds{instance=\"192.168.100.115:9478\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"192.168.100.113:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"192.168.100.114:9478\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"192.168.100.115:9478\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}